### ISSUE TITLE
[PE-D][Tester D] Wrong command word for add meeting function in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-1/tp#176]
Under the adding a meeting command section (page 7 of User Guide), The command that is listed in the header is `add` instead of `addMeeting`.

The description and examples uses `addMeeting` too. This might cause confusion to users!

Perhaps you could update this to prevent confusion!

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/8295843a-78b4-4d23-8638-02a937c2cc53.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ZhiWei1010/ped#4

**Comment by itstrueitstrueitsrealitsreal** [comment]
Duplicate of #173
