### ISSUE TITLE
[PE-D][Tester A] [Application] Edit command: error message for invalid client index 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-1/tp#202]
![Screenshot 2024-04-05 at 4.48.08 PM.png](https://raw.githubusercontent.com/GiselleTan/ped/main/files/48b22e5c-13b7-4d64-a3a4-835f430f1496.png)

The error message indicates "person" instead of "client", which does not match up with the application and user guide of referring to all contacts as clients.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: GiselleTan/ped#16

**Comment by itstrueitstrueitsrealitsreal** [comment]
Noted, seems like more of a feature flaw as compared to a functionality bug that persons and clients are used interchangeably. Will add to our documentation that clients and persons are meant to be used interchangeably.
