### ISSUE TITLE
[PE-D][Tester A] [Application] List command: Success message formatting

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-1/tp#205]
![Screenshot 2024-04-05 at 4.50.54 PM.png](https://raw.githubusercontent.com/GiselleTan/ped/main/files/e00004d0-4e77-4b88-aba5-8efe1ecfdba3.png)

The error message indicates "person" instead of "client", which does not match up with the application and user guide of referring to all contacts as clients.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: GiselleTan/ped#17

**Comment by itstrueitstrueitsrealitsreal** [comment]
Addressed in #202
