### ISSUE TITLE
[PE-D][Tester E] Consider using page breaks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-1/tp#211]
Some parts of the UG was split between the header and the body. It would be better if the entire section starts off from a new page instead, and that can be done using page breaks.

![Screenshot 2024-04-05 at 16.53.18.png](https://raw.githubusercontent.com/tohlh/ped/main/files/8f72e460-aac9-48e4-9395-72f61e941e47.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: tohlh/ped#6

**Comment by itstrueitstrueitsrealitsreal** [comment]
As per the 2103 website:

> The PDF versions of the UG/DG should be usable by the target readers, even if not as neat/optimized as the Web versions. For example, margins and page breaks need not be optimized, but they should not hinder the reader either. Assume some will occasionally choose the PDF version over the Web version e.g, for printing, offline viewing, annotating etc.
