### ISSUE TITLE
[PE-D][Tester B] Edit meeting command not working as advertised

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-1/tp#237]
![Screenshot 2024-04-05 183503.png](https://raw.githubusercontent.com/Ko-Khan/ped/main/files/84ff278e-452a-4ab1-aab0-2b58d4f071a8.png)
In the ug, the user is told that descriptions can be removed by typing d/ without nothing behind it. However, doing so gives us this:

![Screenshot 2024-04-05 183426.png](https://raw.githubusercontent.com/Ko-Khan/ped/main/files/6bbe6e70-fb1f-4e40-be83-ece07c2ee050.png)
Perhaps, this may have been a typo in the user guide, but the app is not working as described in the user guide.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Ko-Khan/ped#16

**Comment by timothysashimi** [comment]
Thank you for pointing this out. Actually it was a documentation error as the editMeeting command needs all parameters present to be parsed (client index, meeting index, description and datetime). The description cannot be empty as only meaningful meetings can be present. As financial advisors, every second is precious. Hence we've edited the user guide as well as included an error message if any of the parameters are missing.
