### ISSUE TITLE
[PE-D][Tester D] Invalid meeting number not displaying correctly for editMeeting

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-1/tp#240]
when an invalid meeting id is executed with the editMeeting command, the error message is unable to display the invalid meting id properly but displays `%1$d`.

steps to reproduce:
1. execute `editMeeting clientIndex/1 meetingIndex/2 n/starbucks meeting dt/01-01-2025 12:00` [note that meetingIndex is invalid while all other fields are valid]

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/264f9625-692d-45b4-9a19-7813c441907d.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ZhiWei1010/ped#21

**Comment by timothysashimi** [comment]
Thank you for pointing this out. We have changed the error message to "Meeting not found". The index number in the error message would be unnecessary as the user knows what index he keyed in from the command.
